### ISSUE TITLE
mobley_352111 and mobley_4689084 are the same molecule

### ISSUE THREAD

**Issue by leeping** [choderalab/FreeSolv#6]
These two molecules have the same IUPAC name, SMILES string, identical experimental values and nearly identical calculated values.  I think these are the only two entries in the set where the molecules are the same by the above criteria.

A few things are different such as the uncertainty estimate and the citation.  I'm wondering if we should remove one of the entries?

**Comment by davidlmobley** [comment]
This was resolved 10/24/14 but I did not close the issue. Closing now.
